### ISSUE TITLE
Missing CORS header preventing login

### ISSUE THREAD

**Issue by pommetjehorlepiep** [snypy/snypy-docker#27] opened 2024-01-13 10:31 UTC
Following the instructions using `docker compose` to start SnyPy on Docker leads
to a running version of SnyPy, but am not able to login using 'admin' /  '12345678!'.

Reason being, that CORS headers are missing...

This is basically after following the Setup Instructions as per  https://github.com/snypy/snypy-docker#setup-application and disabling SENTRY

![image](https://github.com/snypy/snypy-docker/assets/8982487/dadbdfd6-ba6a-4dfb-a798-3597326102fa)

**Comment by nezhar** [comment] 2024-04-14 16:51
Did you configured the `CORS_ORIGIN_WHITELIST` in your `docker-compose.override.yml`?

An exmaple can be found [here](https://github.com/snypy/snypy-docker/blob/main/docker-compose.override.example.yml#L10)

**Comment by nezhar** [comment] 2024-07-13 14:43
Since I cannot reproduce this issue I'm going to close it.

**Closed by nezhar** 2024-07-13 14:43 UTC
